package it.eng.parer.fascicolo.jpa.grantedEntity;

import java.io.Serializable;

import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "APL_TIPO_ORGANIZ")
public class SIAplTipoOrganiz implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private SIAplApplic sIAplApplic;
    private String flLastLivello;
    private Long idTipoOrganiz;
    private String nmTipoOrganiz;

    public SIAplTipoOrganiz() {
    }

    public SIAplTipoOrganiz(Long idTipoOrganiz) {
        this.idTipoOrganiz = idTipoOrganiz;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_APPLIC")
    public SIAplApplic getsIAplApplic() {
        return sIAplApplic;
    }

    public void setsIAplApplic(SIAplApplic sIAplApplic) {
        this.sIAplApplic = sIAplApplic;
    }

    @Basic
    @Column(name = "FL_LAST_LIVELLO", nullable = false, length = 1, columnDefinition = "CHAR")
    public String getFlLastLivello() {
        return flLastLivello;
    }

    public void setFlLastLivello(String flLastLivello) {
        this.flLastLivello = flLastLivello;
    }

    @Id
    @Column(name = "ID_TIPO_ORGANIZ")
    public Long getIdTipoOrganiz() {
        return idTipoOrganiz;
    }

    public void setIdTipoOrganiz(Long idTipoOrganiz) {
        this.idTipoOrganiz = idTipoOrganiz;
    }

    @Basic
    @Column(name = "NM_TIPO_ORGANIZ", nullable = false, length = 100)
    public String getNmTipoOrganiz() {
        return nmTipoOrganiz;
    }

    public void setNmTipoOrganiz(String nmTipoOrganiz) {
        this.nmTipoOrganiz = nmTipoOrganiz;
    }
}
